version: 2.1

# Je veux build mon projet sur une image docker

jobs:
  build:
    description: Build the docker images
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build the docker images
          command: |
            docker build -t $DOCKERHUB_USERNAME/app-sample-js:latest .

      - run:
          name: Push application Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/app-sample-js:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master