version: 2.1

# Je veux build mon projet sur une image docker

jobs:
  build:
    description: Build the docker images
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Build the docker images
          command: |
            docker build -t $DOCKERHUB_USERNAME/app-sample-js:latest .

      - run:
          name: Push application Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/app-sample-js:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master