version: 2.1

# Je veux build mon projet sur une image docker

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build:
    description: Build the docker images
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true 
    steps:
      - checkout
      - docker/publish:
          docker-password: $DOCKERHUB_PASSWORD
          docker-username: $DOCKERHUB_USERNAME
          image: $DOCKERHUB_USERNAME/app-sample-js
          tag: 0.1.$CIRCLE_BUILD_NUM

workflows:
  build-docker-image:
    jobs:
      - build

    